// Copyright 2017 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// https://developers.google.com/protocol-buffers/docs/proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: maintner.proto

package maintpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubIssue   *GithubIssueMutation   `protobuf:"bytes,1,opt,name=github_issue,json=githubIssue,proto3" json:"github_issue,omitempty"` // issue-specific changes
	Github        *GithubMutation        `protobuf:"bytes,3,opt,name=github,proto3" json:"github,omitempty"`                              // labels, milestones (not issue-specific)
	Git           *GitMutation           `protobuf:"bytes,2,opt,name=git,proto3" json:"git,omitempty"`
	Gerrit        *GerritMutation        `protobuf:"bytes,4,opt,name=gerrit,proto3" json:"gerrit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_maintner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetGithubIssue() *GithubIssueMutation {
	if x != nil {
		return x.GithubIssue
	}
	return nil
}

func (x *Mutation) GetGithub() *GithubMutation {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *Mutation) GetGit() *GitMutation {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *Mutation) GetGerrit() *GerritMutation {
	if x != nil {
		return x.Gerrit
	}
	return nil
}

type GithubMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Owner string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"` // "golang"
	Repo  string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`   // "go"
	// Updated labels. (All must have id set at least)
	Labels []*GithubLabel `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	// Updated milestones. (All must have id set at least)
	Milestones    []*GithubMilestone `protobuf:"bytes,4,rep,name=milestones,proto3" json:"milestones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubMutation) Reset() {
	*x = GithubMutation{}
	mi := &file_maintner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubMutation) ProtoMessage() {}

func (x *GithubMutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubMutation.ProtoReflect.Descriptor instead.
func (*GithubMutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{1}
}

func (x *GithubMutation) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubMutation) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GithubMutation) GetLabels() []*GithubLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GithubMutation) GetMilestones() []*GithubMilestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

type GithubIssueMutation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Owner  string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`    // "golang"
	Repo   string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`      // "go"
	Number int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"` // 1, 2, 3... (not the ID)
	// not_exist is set true if the issue has been found to not exist.
	// If true, the owner/repo/number fields above must still be set.
	// If a future issue mutation for the same number arrives without
	// not_exist set, then the issue comes back to life.
	NotExist         bool                   `protobuf:"varint,13,opt,name=not_exist,json=notExist,proto3" json:"not_exist,omitempty"`
	Id               int64                  `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`                                                            // unique across all repos
	User             *GithubUser            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                                          // only set for new/updated issues, not new comments
	Assignees        []*GithubUser          `protobuf:"bytes,10,rep,name=assignees,proto3" json:"assignees,omitempty"`                                               // who the issue is assigned to
	DeletedAssignees []int64                `protobuf:"varint,11,rep,packed,name=deleted_assignees,json=deletedAssignees,proto3" json:"deleted_assignees,omitempty"` // IDs of users to delete from the assignee list
	Created          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`                                                    // only needed on new issues
	Updated          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`                                                    // only set on updated issue text
	Title            string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`                                                        // issue title
	// body_change changes the body field (the top post, which isn't a comment).
	// It is now used in preference to the old body field.
	BodyChange *StringChange `protobuf:"bytes,31,opt,name=body_change,json=bodyChange,proto3" json:"body_change,omitempty"`
	// body was the old way to change the body, but it doesn't support removing the
	// body text, which is common on PRs. New mutations use body_change instead.
	Body        string `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	NoMilestone bool   `protobuf:"varint,15,opt,name=no_milestone,json=noMilestone,proto3" json:"no_milestone,omitempty"` // true unsets any previously-set milestone; false ignored.
	// When setting a milestone, only the milestone_id must be set.
	// TODO: allow num or title to be used if Github only returns those? So far unneeded.
	// The num and title, if non-zero, are treated as if they were a GithubMutation.Milestone update.
	MilestoneId       int64                         `protobuf:"varint,16,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`    // sets milestone to this milestone id (e.g. 2386495, global?)
	MilestoneNum      int64                         `protobuf:"varint,17,opt,name=milestone_num,json=milestoneNum,proto3" json:"milestone_num,omitempty"` // sets milestone to this milestone number (e.g. 2, per-repo)
	MilestoneTitle    string                        `protobuf:"bytes,18,opt,name=milestone_title,json=milestoneTitle,proto3" json:"milestone_title,omitempty"`
	Closed            *BoolChange                   `protobuf:"bytes,19,opt,name=closed,proto3" json:"closed,omitempty"`
	Locked            *BoolChange                   `protobuf:"bytes,25,opt,name=locked,proto3" json:"locked,omitempty"`
	PullRequest       bool                          `protobuf:"varint,28,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"` // true is the issue is a Pull Request
	ClosedAt          *timestamppb.Timestamp        `protobuf:"bytes,21,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	ClosedBy          *GithubUser                   `protobuf:"bytes,22,opt,name=closed_by,json=closedBy,proto3" json:"closed_by,omitempty"`
	RemoveLabel       []int64                       `protobuf:"varint,23,rep,packed,name=remove_label,json=removeLabel,proto3" json:"remove_label,omitempty"` // label IDs to remove
	AddLabel          []*GithubLabel                `protobuf:"bytes,24,rep,name=add_label,json=addLabel,proto3" json:"add_label,omitempty"`
	Comment           []*GithubIssueCommentMutation `protobuf:"bytes,8,rep,name=comment,proto3" json:"comment,omitempty"`
	CommentStatus     *GithubIssueSyncStatus        `protobuf:"bytes,14,opt,name=comment_status,json=commentStatus,proto3" json:"comment_status,omitempty"`
	Event             []*GithubIssueEvent           `protobuf:"bytes,26,rep,name=event,proto3" json:"event,omitempty"` // new events to add
	EventStatus       *GithubIssueSyncStatus        `protobuf:"bytes,27,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Review            []*GithubReview               `protobuf:"bytes,29,rep,name=review,proto3" json:"review,omitempty"` // new reviews to add
	ReviewStatus      *GithubIssueSyncStatus        `protobuf:"bytes,30,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	Reaction          []*GithubReaction             `protobuf:"bytes,32,rep,name=reaction,proto3" json:"reaction,omitempty"`                                                      // reactions on the issue body
	RemovedReactionId []int64                       `protobuf:"varint,33,rep,packed,name=removed_reaction_id,json=removedReactionId,proto3" json:"removed_reaction_id,omitempty"` // reaction IDs removed from the issue body
	ReactionStatus    *GithubIssueSyncStatus        `protobuf:"bytes,34,opt,name=reaction_status,json=reactionStatus,proto3" json:"reaction_status,omitempty"`                    // sync cursor for reactions
	// PR-specific fields. Only set when pull_request is true.
	Draft           *BoolChange              `protobuf:"bytes,35,opt,name=draft,proto3" json:"draft,omitempty"`
	Merged          *BoolChange              `protobuf:"bytes,36,opt,name=merged,proto3" json:"merged,omitempty"`
	MergedAt        *timestamppb.Timestamp   `protobuf:"bytes,37,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
	MergedBy        *GithubUser              `protobuf:"bytes,38,opt,name=merged_by,json=mergedBy,proto3" json:"merged_by,omitempty"`
	MergeCommitHash string                   `protobuf:"bytes,39,opt,name=merge_commit_hash,json=mergeCommitHash,proto3" json:"merge_commit_hash,omitempty"`
	Head            *GithubPullRequestBranch `protobuf:"bytes,40,opt,name=head,proto3" json:"head,omitempty"`                                             // source branch
	Base            *GithubPullRequestBranch `protobuf:"bytes,41,opt,name=base,proto3" json:"base,omitempty"`                                             // target branch
	PrDetailStatus  *GithubIssueSyncStatus   `protobuf:"bytes,42,opt,name=pr_detail_status,json=prDetailStatus,proto3" json:"pr_detail_status,omitempty"` // sync cursor for PR detail fetch
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GithubIssueMutation) Reset() {
	*x = GithubIssueMutation{}
	mi := &file_maintner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubIssueMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIssueMutation) ProtoMessage() {}

func (x *GithubIssueMutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIssueMutation.ProtoReflect.Descriptor instead.
func (*GithubIssueMutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{2}
}

func (x *GithubIssueMutation) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubIssueMutation) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GithubIssueMutation) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GithubIssueMutation) GetNotExist() bool {
	if x != nil {
		return x.NotExist
	}
	return false
}

func (x *GithubIssueMutation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubIssueMutation) GetUser() *GithubUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GithubIssueMutation) GetAssignees() []*GithubUser {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *GithubIssueMutation) GetDeletedAssignees() []int64 {
	if x != nil {
		return x.DeletedAssignees
	}
	return nil
}

func (x *GithubIssueMutation) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *GithubIssueMutation) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *GithubIssueMutation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GithubIssueMutation) GetBodyChange() *StringChange {
	if x != nil {
		return x.BodyChange
	}
	return nil
}

func (x *GithubIssueMutation) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GithubIssueMutation) GetNoMilestone() bool {
	if x != nil {
		return x.NoMilestone
	}
	return false
}

func (x *GithubIssueMutation) GetMilestoneId() int64 {
	if x != nil {
		return x.MilestoneId
	}
	return 0
}

func (x *GithubIssueMutation) GetMilestoneNum() int64 {
	if x != nil {
		return x.MilestoneNum
	}
	return 0
}

func (x *GithubIssueMutation) GetMilestoneTitle() string {
	if x != nil {
		return x.MilestoneTitle
	}
	return ""
}

func (x *GithubIssueMutation) GetClosed() *BoolChange {
	if x != nil {
		return x.Closed
	}
	return nil
}

func (x *GithubIssueMutation) GetLocked() *BoolChange {
	if x != nil {
		return x.Locked
	}
	return nil
}

func (x *GithubIssueMutation) GetPullRequest() bool {
	if x != nil {
		return x.PullRequest
	}
	return false
}

func (x *GithubIssueMutation) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *GithubIssueMutation) GetClosedBy() *GithubUser {
	if x != nil {
		return x.ClosedBy
	}
	return nil
}

func (x *GithubIssueMutation) GetRemoveLabel() []int64 {
	if x != nil {
		return x.RemoveLabel
	}
	return nil
}

func (x *GithubIssueMutation) GetAddLabel() []*GithubLabel {
	if x != nil {
		return x.AddLabel
	}
	return nil
}

func (x *GithubIssueMutation) GetComment() []*GithubIssueCommentMutation {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *GithubIssueMutation) GetCommentStatus() *GithubIssueSyncStatus {
	if x != nil {
		return x.CommentStatus
	}
	return nil
}

func (x *GithubIssueMutation) GetEvent() []*GithubIssueEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GithubIssueMutation) GetEventStatus() *GithubIssueSyncStatus {
	if x != nil {
		return x.EventStatus
	}
	return nil
}

func (x *GithubIssueMutation) GetReview() []*GithubReview {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *GithubIssueMutation) GetReviewStatus() *GithubIssueSyncStatus {
	if x != nil {
		return x.ReviewStatus
	}
	return nil
}

func (x *GithubIssueMutation) GetReaction() []*GithubReaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *GithubIssueMutation) GetRemovedReactionId() []int64 {
	if x != nil {
		return x.RemovedReactionId
	}
	return nil
}

func (x *GithubIssueMutation) GetReactionStatus() *GithubIssueSyncStatus {
	if x != nil {
		return x.ReactionStatus
	}
	return nil
}

func (x *GithubIssueMutation) GetDraft() *BoolChange {
	if x != nil {
		return x.Draft
	}
	return nil
}

func (x *GithubIssueMutation) GetMerged() *BoolChange {
	if x != nil {
		return x.Merged
	}
	return nil
}

func (x *GithubIssueMutation) GetMergedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MergedAt
	}
	return nil
}

func (x *GithubIssueMutation) GetMergedBy() *GithubUser {
	if x != nil {
		return x.MergedBy
	}
	return nil
}

func (x *GithubIssueMutation) GetMergeCommitHash() string {
	if x != nil {
		return x.MergeCommitHash
	}
	return ""
}

func (x *GithubIssueMutation) GetHead() *GithubPullRequestBranch {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GithubIssueMutation) GetBase() *GithubPullRequestBranch {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GithubIssueMutation) GetPrDetailStatus() *GithubIssueSyncStatus {
	if x != nil {
		return x.PrDetailStatus
	}
	return nil
}

// BoolChange represents a change to a boolean value.
// (Notably, the wrapper type permits representing a change to false.)
type BoolChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           bool                   `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolChange) Reset() {
	*x = BoolChange{}
	mi := &file_maintner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolChange) ProtoMessage() {}

func (x *BoolChange) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolChange.ProtoReflect.Descriptor instead.
func (*BoolChange) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{3}
}

func (x *BoolChange) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

// StringChange represents a change to a boolean value.
// (Notably, the wrapper type permits representing a change to the empty string.)
type StringChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringChange) Reset() {
	*x = StringChange{}
	mi := &file_maintner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringChange) ProtoMessage() {}

func (x *StringChange) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringChange.ProtoReflect.Descriptor instead.
func (*StringChange) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{4}
}

func (x *StringChange) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type GithubLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubLabel) Reset() {
	*x = GithubLabel{}
	mi := &file_maintner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubLabel) ProtoMessage() {}

func (x *GithubLabel) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubLabel.ProtoReflect.Descriptor instead.
func (*GithubLabel) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{5}
}

func (x *GithubLabel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GithubMilestone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // required
	// Following only need to be non-zero on changes:
	Title         string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Closed        *BoolChange `protobuf:"bytes,3,opt,name=closed,proto3" json:"closed,omitempty"`
	Number        int64       `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubMilestone) Reset() {
	*x = GithubMilestone{}
	mi := &file_maintner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubMilestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubMilestone) ProtoMessage() {}

func (x *GithubMilestone) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubMilestone.ProtoReflect.Descriptor instead.
func (*GithubMilestone) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{6}
}

func (x *GithubMilestone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubMilestone) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GithubMilestone) GetClosed() *BoolChange {
	if x != nil {
		return x.Closed
	}
	return nil
}

func (x *GithubMilestone) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// See https://developer.github.com/v3/activity/events/types/#issuesevent
// for some info.
type GithubIssueEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required:
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// event_type can be one of "assigned", "unassigned", "labeled",
	// "unlabeled", "opened", "edited", "milestoned", "demilestoned",
	// "closed", "reopened", "referenced", "renamed" or anything else
	// that Github adds in the future.
	EventType string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorId   int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Created   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"` // time of the event
	// label is populated for "labeled" and "unlabeled" events.
	// The label will usually not have an ID, due to Github's API
	// not returning one.
	Label *GithubLabel `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	// milestone is populated for "milestoned" and "demilestoned" events.
	// The label will usually not have an ID, due to Github's API
	// not returning one.
	Milestone *GithubMilestone `protobuf:"bytes,6,opt,name=milestone,proto3" json:"milestone,omitempty"`
	// For "assigned", "unassigned":
	AssigneeId int64 `protobuf:"varint,7,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"` // always same as actor_id it seems? Github API doesn't say.
	AssignerId int64 `protobuf:"varint,8,opt,name=assigner_id,json=assignerId,proto3" json:"assigner_id,omitempty"`
	// For "referenced", "closed":
	Commit *GithubCommit `protobuf:"bytes,9,opt,name=commit,proto3" json:"commit,omitempty"`
	// For "renamed" events:
	RenameFrom        string      `protobuf:"bytes,11,opt,name=rename_from,json=renameFrom,proto3" json:"rename_from,omitempty"`
	RenameTo          string      `protobuf:"bytes,12,opt,name=rename_to,json=renameTo,proto3" json:"rename_to,omitempty"`
	ReviewerId        int64       `protobuf:"varint,13,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	ReviewRequesterId int64       `protobuf:"varint,14,opt,name=review_requester_id,json=reviewRequesterId,proto3" json:"review_requester_id,omitempty"`
	TeamReviewer      *GithubTeam `protobuf:"bytes,16,opt,name=team_reviewer,json=teamReviewer,proto3" json:"team_reviewer,omitempty"`
	// Contents of a dismissed review event, see dismissed_review in
	// https://developer.github.com/v3/issues/events/ for more info
	DismissedReview *GithubDismissedReviewEvent `protobuf:"bytes,15,opt,name=dismissed_review,json=dismissedReview,proto3" json:"dismissed_review,omitempty"`
	// other_json is usually empty. If Github adds event types or fields
	// in the future, this captures those added fields. If non-empty it
	// will be a JSON object with the fields that weren't understood.
	OtherJson     []byte `protobuf:"bytes,10,opt,name=other_json,json=otherJson,proto3" json:"other_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubIssueEvent) Reset() {
	*x = GithubIssueEvent{}
	mi := &file_maintner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubIssueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIssueEvent) ProtoMessage() {}

func (x *GithubIssueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIssueEvent.ProtoReflect.Descriptor instead.
func (*GithubIssueEvent) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{7}
}

func (x *GithubIssueEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubIssueEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GithubIssueEvent) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *GithubIssueEvent) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *GithubIssueEvent) GetLabel() *GithubLabel {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *GithubIssueEvent) GetMilestone() *GithubMilestone {
	if x != nil {
		return x.Milestone
	}
	return nil
}

func (x *GithubIssueEvent) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

func (x *GithubIssueEvent) GetAssignerId() int64 {
	if x != nil {
		return x.AssignerId
	}
	return 0
}

func (x *GithubIssueEvent) GetCommit() *GithubCommit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *GithubIssueEvent) GetRenameFrom() string {
	if x != nil {
		return x.RenameFrom
	}
	return ""
}

func (x *GithubIssueEvent) GetRenameTo() string {
	if x != nil {
		return x.RenameTo
	}
	return ""
}

func (x *GithubIssueEvent) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

func (x *GithubIssueEvent) GetReviewRequesterId() int64 {
	if x != nil {
		return x.ReviewRequesterId
	}
	return 0
}

func (x *GithubIssueEvent) GetTeamReviewer() *GithubTeam {
	if x != nil {
		return x.TeamReviewer
	}
	return nil
}

func (x *GithubIssueEvent) GetDismissedReview() *GithubDismissedReviewEvent {
	if x != nil {
		return x.DismissedReview
	}
	return nil
}

func (x *GithubIssueEvent) GetOtherJson() []byte {
	if x != nil {
		return x.OtherJson
	}
	return nil
}

// Contents of a dismissed review event - when someone leaves a
// review requesting changes and someone else dismisses it. See
// https://developer.github.com/v3/issues/events for more information.
type GithubDismissedReviewEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReviewId         int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"` // ID of the review being dismissed
	DismissalMessage string                 `protobuf:"bytes,3,opt,name=dismissal_message,json=dismissalMessage,proto3" json:"dismissal_message,omitempty"`
	State            string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // commented, approved, changes_requested
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GithubDismissedReviewEvent) Reset() {
	*x = GithubDismissedReviewEvent{}
	mi := &file_maintner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubDismissedReviewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubDismissedReviewEvent) ProtoMessage() {}

func (x *GithubDismissedReviewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubDismissedReviewEvent.ProtoReflect.Descriptor instead.
func (*GithubDismissedReviewEvent) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{8}
}

func (x *GithubDismissedReviewEvent) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *GithubDismissedReviewEvent) GetDismissalMessage() string {
	if x != nil {
		return x.DismissalMessage
	}
	return ""
}

func (x *GithubDismissedReviewEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GithubCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                       // "golang"
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`                         // "go"
	CommitId      string                 `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"` // "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubCommit) Reset() {
	*x = GithubCommit{}
	mi := &file_maintner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubCommit) ProtoMessage() {}

func (x *GithubCommit) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubCommit.ProtoReflect.Descriptor instead.
func (*GithubCommit) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{9}
}

func (x *GithubCommit) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubCommit) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GithubCommit) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

// Contents of a pull request review - when someone
// comments, requests changes, or approves changes
// on a pull request. See
// https://developer.github.com/v3/pulls/reviews/ for more information.
type GithubReview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required:
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActorId          int64                  `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Created          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"` // time of the event
	Body             string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`       // body of the review comment
	State            string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`     // COMMENTED, APPROVED, CHANGES_REQUESTED
	CommitId         string                 `protobuf:"bytes,6,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	ActorAssociation string                 `protobuf:"bytes,7,opt,name=actor_association,json=actorAssociation,proto3" json:"actor_association,omitempty"`
	// other_json is usually empty.
	OtherJson     []byte `protobuf:"bytes,8,opt,name=other_json,json=otherJson,proto3" json:"other_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubReview) Reset() {
	*x = GithubReview{}
	mi := &file_maintner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubReview) ProtoMessage() {}

func (x *GithubReview) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubReview.ProtoReflect.Descriptor instead.
func (*GithubReview) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{10}
}

func (x *GithubReview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubReview) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *GithubReview) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *GithubReview) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GithubReview) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GithubReview) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *GithubReview) GetActorAssociation() string {
	if x != nil {
		return x.ActorAssociation
	}
	return ""
}

func (x *GithubReview) GetOtherJson() []byte {
	if x != nil {
		return x.OtherJson
	}
	return nil
}

// GithubIssueSyncStatus notes where syncing is at for comments
// on an issue,
// This mutation type is only made at/after the same top-level mutation
// which created the corresponding comments.
type GithubIssueSyncStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_date is the "Date" response header from Github for the
	// final HTTP response.
	ServerDate    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_date,json=serverDate,proto3" json:"server_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubIssueSyncStatus) Reset() {
	*x = GithubIssueSyncStatus{}
	mi := &file_maintner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubIssueSyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIssueSyncStatus) ProtoMessage() {}

func (x *GithubIssueSyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIssueSyncStatus.ProtoReflect.Descriptor instead.
func (*GithubIssueSyncStatus) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{11}
}

func (x *GithubIssueSyncStatus) GetServerDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerDate
	}
	return nil
}

type GithubIssueCommentMutation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User              *GithubUser            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`       // not present in edits later
	Body              string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`       // may not be present in edits later
	Created           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"` // not present in edits later
	Updated           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Reaction          []*GithubReaction      `protobuf:"bytes,6,rep,name=reaction,proto3" json:"reaction,omitempty"`                                                      // reactions on this comment
	RemovedReactionId []int64                `protobuf:"varint,7,rep,packed,name=removed_reaction_id,json=removedReactionId,proto3" json:"removed_reaction_id,omitempty"` // reaction IDs removed from this comment
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GithubIssueCommentMutation) Reset() {
	*x = GithubIssueCommentMutation{}
	mi := &file_maintner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubIssueCommentMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubIssueCommentMutation) ProtoMessage() {}

func (x *GithubIssueCommentMutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubIssueCommentMutation.ProtoReflect.Descriptor instead.
func (*GithubIssueCommentMutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{12}
}

func (x *GithubIssueCommentMutation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubIssueCommentMutation) GetUser() *GithubUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GithubIssueCommentMutation) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GithubIssueCommentMutation) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *GithubIssueCommentMutation) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *GithubIssueCommentMutation) GetReaction() []*GithubReaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *GithubIssueCommentMutation) GetRemovedReactionId() []int64 {
	if x != nil {
		return x.RemovedReactionId
	}
	return nil
}

type GithubUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubUser) Reset() {
	*x = GithubUser{}
	mi := &file_maintner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubUser) ProtoMessage() {}

func (x *GithubUser) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubUser.ProtoReflect.Descriptor instead.
func (*GithubUser) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{13}
}

func (x *GithubUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubUser) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GithubReaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // "+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubReaction) Reset() {
	*x = GithubReaction{}
	mi := &file_maintner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubReaction) ProtoMessage() {}

func (x *GithubReaction) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubReaction.ProtoReflect.Descriptor instead.
func (*GithubReaction) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{14}
}

func (x *GithubReaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubReaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GithubReaction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GithubReaction) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type GithubTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubTeam) Reset() {
	*x = GithubTeam{}
	mi := &file_maintner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubTeam) ProtoMessage() {}

func (x *GithubTeam) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubTeam.ProtoReflect.Descriptor instead.
func (*GithubTeam) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{15}
}

func (x *GithubTeam) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GithubTeam) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// GithubPullRequestBranch identifies a branch in a pull request (head or base).
type GithubPullRequestBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`     // branch name, e.g. "main" or "feature-x"
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`   // commit SHA
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"` // repo owner (may differ from issue owner for fork PRs)
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`   // repo name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubPullRequestBranch) Reset() {
	*x = GithubPullRequestBranch{}
	mi := &file_maintner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubPullRequestBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubPullRequestBranch) ProtoMessage() {}

func (x *GithubPullRequestBranch) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubPullRequestBranch.ProtoReflect.Descriptor instead.
func (*GithubPullRequestBranch) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{16}
}

func (x *GithubPullRequestBranch) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GithubPullRequestBranch) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GithubPullRequestBranch) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GithubPullRequestBranch) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GitMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  *GitRepo               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// commit adds a commit, or adds new information to a commit if fields
	// are added in the future.
	Commit *GitCommit `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// ref_update records that a ref now points to a given hash.
	RefUpdate *GitRef `protobuf:"bytes,3,opt,name=ref_update,json=refUpdate,proto3" json:"ref_update,omitempty"`
	// tag adds an annotated tag object.
	Tag           *GitTag `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitMutation) Reset() {
	*x = GitMutation{}
	mi := &file_maintner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitMutation) ProtoMessage() {}

func (x *GitMutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitMutation.ProtoReflect.Descriptor instead.
func (*GitMutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{17}
}

func (x *GitMutation) GetRepo() *GitRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GitMutation) GetCommit() *GitCommit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *GitMutation) GetRefUpdate() *GitRef {
	if x != nil {
		return x.RefUpdate
	}
	return nil
}

func (x *GitMutation) GetTag() *GitTag {
	if x != nil {
		return x.Tag
	}
	return nil
}

// GitRepo identifies a git repo being mutated.
type GitRepo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If go_repo is set, it identifies a go.googlesource.com/<go_repo> repo.
	GoRepo string `protobuf:"bytes,1,opt,name=go_repo,json=goRepo,proto3" json:"go_repo,omitempty"`
	// name is an arbitrary repo name, e.g. "tailscale/tailscale".
	// If set, go_repo is ignored.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRepo) Reset() {
	*x = GitRepo{}
	mi := &file_maintner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepo) ProtoMessage() {}

func (x *GitRepo) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRepo.ProtoReflect.Descriptor instead.
func (*GitRepo) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{18}
}

func (x *GitRepo) GetGoRepo() string {
	if x != nil {
		return x.GoRepo
	}
	return ""
}

func (x *GitRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GitCommit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash is the full lowercase hex object hash.
	// Typically 40 hex bytes (SHA-1) but may be longer for SHA-256 repos.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// raw is the "git cat-file commit <hash>" output.
	Raw           []byte       `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	DiffTree      *GitDiffTree `protobuf:"bytes,3,opt,name=diff_tree,json=diffTree,proto3" json:"diff_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCommit) Reset() {
	*x = GitCommit{}
	mi := &file_maintner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCommit) ProtoMessage() {}

func (x *GitCommit) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCommit.ProtoReflect.Descriptor instead.
func (*GitCommit) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{19}
}

func (x *GitCommit) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GitCommit) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *GitCommit) GetDiffTree() *GitDiffTree {
	if x != nil {
		return x.DiffTree
	}
	return nil
}

// git diff-tree --numstat oldtree newtree
type GitDiffTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []*GitDiffTreeFile     `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffTree) Reset() {
	*x = GitDiffTree{}
	mi := &file_maintner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffTree) ProtoMessage() {}

func (x *GitDiffTree) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffTree.ProtoReflect.Descriptor instead.
func (*GitDiffTree) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{20}
}

func (x *GitDiffTree) GetFile() []*GitDiffTreeFile {
	if x != nil {
		return x.File
	}
	return nil
}

// GitDiffTreeFile represents one line of `git diff-tree --numstat` output.
type GitDiffTreeFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Added         int64                  `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"`
	Deleted       int64                  `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Binary        bool                   `protobuf:"varint,4,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffTreeFile) Reset() {
	*x = GitDiffTreeFile{}
	mi := &file_maintner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffTreeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffTreeFile) ProtoMessage() {}

func (x *GitDiffTreeFile) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffTreeFile.ProtoReflect.Descriptor instead.
func (*GitDiffTreeFile) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{21}
}

func (x *GitDiffTreeFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GitDiffTreeFile) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *GitDiffTreeFile) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *GitDiffTreeFile) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

// GitTag represents an annotated tag object. Lightweight tags do not have
// a tag object; they are just a ref pointing directly at a commit and are
// recorded only as a GitRef ref_update, not as a GitTag.
//
// For annotated tags, the ref (e.g. "refs/tags/v1.0") points to the tag
// object (hash), which in turn points to the tagged commit (target_hash).
type GitTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash is the annotated tag object's own hex hash.
	// Typically 40 hex bytes (SHA-1) but may be longer for SHA-256 repos.
	// This is what the refs/tags/<name> ref points to.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// raw is the "git cat-file tag <hash>" output, containing the tag's
	// headers (object, type, tag, tagger) and the tag message.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// target_hash is the hex hash of the object this tag points to.
	// For the common case this is a commit hash. In rare cases a tag can
	// point to a tree, blob, or even another tag object.
	// Typically 40 hex bytes (SHA-1).
	TargetHash    string `protobuf:"bytes,3,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitTag) Reset() {
	*x = GitTag{}
	mi := &file_maintner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitTag) ProtoMessage() {}

func (x *GitTag) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitTag.ProtoReflect.Descriptor instead.
func (*GitTag) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{22}
}

func (x *GitTag) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GitTag) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *GitTag) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

type GerritMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the Gerrit server and project, without scheme (https implied) or
	// trailing slash.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // "go.googlesource.com/go", "go.googlesource.com/net", etc
	// Commits to add.
	Commits []*GitCommit `protobuf:"bytes,2,rep,name=commits,proto3" json:"commits,omitempty"`
	// git refs to update.
	Refs []*GitRef `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
	// deleted_refs are ref names to delete.
	DeletedRefs   []string `protobuf:"bytes,4,rep,name=deleted_refs,json=deletedRefs,proto3" json:"deleted_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GerritMutation) Reset() {
	*x = GerritMutation{}
	mi := &file_maintner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GerritMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GerritMutation) ProtoMessage() {}

func (x *GerritMutation) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GerritMutation.ProtoReflect.Descriptor instead.
func (*GerritMutation) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{23}
}

func (x *GerritMutation) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GerritMutation) GetCommits() []*GitCommit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *GerritMutation) GetRefs() []*GitRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *GerritMutation) GetDeletedRefs() []string {
	if x != nil {
		return x.DeletedRefs
	}
	return nil
}

type GitRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ref is the git ref name, such as:
	//
	//	HEAD
	//	refs/heads/master
	//	refs/changes/00/14700/1
	//	refs/changes/00/14700/meta
	//	refs/meta/config
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// hash is the lowercase hex object hash.
	// Typically 40 hex bytes (SHA-1) but may be longer for SHA-256 repos.
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRef) Reset() {
	*x = GitRef{}
	mi := &file_maintner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRef) ProtoMessage() {}

func (x *GitRef) ProtoReflect() protoreflect.Message {
	mi := &file_maintner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRef.ProtoReflect.Descriptor instead.
func (*GitRef) Descriptor() ([]byte, []int) {
	return file_maintner_proto_rawDescGZIP(), []int{24}
}

func (x *GitRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_maintner_proto protoreflect.FileDescriptor

const file_maintner_proto_rawDesc = "" +
	"\n" +
	"\x0emaintner.proto\x12\amaintpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\bMutation\x12?\n" +
	"\fgithub_issue\x18\x01 \x01(\v2\x1c.maintpb.GithubIssueMutationR\vgithubIssue\x12/\n" +
	"\x06github\x18\x03 \x01(\v2\x17.maintpb.GithubMutationR\x06github\x12&\n" +
	"\x03git\x18\x02 \x01(\v2\x14.maintpb.GitMutationR\x03git\x12/\n" +
	"\x06gerrit\x18\x04 \x01(\v2\x17.maintpb.GerritMutationR\x06gerrit\"\xa2\x01\n" +
	"\x0eGithubMutation\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12,\n" +
	"\x06labels\x18\x03 \x03(\v2\x14.maintpb.GithubLabelR\x06labels\x128\n" +
	"\n" +
	"milestones\x18\x04 \x03(\v2\x18.maintpb.GithubMilestoneR\n" +
	"milestones\"\xee\x0e\n" +
	"\x13GithubIssueMutation\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x1b\n" +
	"\tnot_exist\x18\r \x01(\bR\bnotExist\x12\x0e\n" +
	"\x02id\x18\f \x01(\x03R\x02id\x12'\n" +
	"\x04user\x18\x04 \x01(\v2\x13.maintpb.GithubUserR\x04user\x121\n" +
	"\tassignees\x18\n" +
	" \x03(\v2\x13.maintpb.GithubUserR\tassignees\x12+\n" +
	"\x11deleted_assignees\x18\v \x03(\x03R\x10deletedAssignees\x124\n" +
	"\acreated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\aupdated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x126\n" +
	"\vbody_change\x18\x1f \x01(\v2\x15.maintpb.StringChangeR\n" +
	"bodyChange\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x12!\n" +
	"\fno_milestone\x18\x0f \x01(\bR\vnoMilestone\x12!\n" +
	"\fmilestone_id\x18\x10 \x01(\x03R\vmilestoneId\x12#\n" +
	"\rmilestone_num\x18\x11 \x01(\x03R\fmilestoneNum\x12'\n" +
	"\x0fmilestone_title\x18\x12 \x01(\tR\x0emilestoneTitle\x12+\n" +
	"\x06closed\x18\x13 \x01(\v2\x13.maintpb.BoolChangeR\x06closed\x12+\n" +
	"\x06locked\x18\x19 \x01(\v2\x13.maintpb.BoolChangeR\x06locked\x12!\n" +
	"\fpull_request\x18\x1c \x01(\bR\vpullRequest\x127\n" +
	"\tclosed_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x120\n" +
	"\tclosed_by\x18\x16 \x01(\v2\x13.maintpb.GithubUserR\bclosedBy\x12!\n" +
	"\fremove_label\x18\x17 \x03(\x03R\vremoveLabel\x121\n" +
	"\tadd_label\x18\x18 \x03(\v2\x14.maintpb.GithubLabelR\baddLabel\x12=\n" +
	"\acomment\x18\b \x03(\v2#.maintpb.GithubIssueCommentMutationR\acomment\x12E\n" +
	"\x0ecomment_status\x18\x0e \x01(\v2\x1e.maintpb.GithubIssueSyncStatusR\rcommentStatus\x12/\n" +
	"\x05event\x18\x1a \x03(\v2\x19.maintpb.GithubIssueEventR\x05event\x12A\n" +
	"\fevent_status\x18\x1b \x01(\v2\x1e.maintpb.GithubIssueSyncStatusR\veventStatus\x12-\n" +
	"\x06review\x18\x1d \x03(\v2\x15.maintpb.GithubReviewR\x06review\x12C\n" +
	"\rreview_status\x18\x1e \x01(\v2\x1e.maintpb.GithubIssueSyncStatusR\freviewStatus\x123\n" +
	"\breaction\x18  \x03(\v2\x17.maintpb.GithubReactionR\breaction\x12.\n" +
	"\x13removed_reaction_id\x18! \x03(\x03R\x11removedReactionId\x12G\n" +
	"\x0freaction_status\x18\" \x01(\v2\x1e.maintpb.GithubIssueSyncStatusR\x0ereactionStatus\x12)\n" +
	"\x05draft\x18# \x01(\v2\x13.maintpb.BoolChangeR\x05draft\x12+\n" +
	"\x06merged\x18$ \x01(\v2\x13.maintpb.BoolChangeR\x06merged\x127\n" +
	"\tmerged_at\x18% \x01(\v2\x1a.google.protobuf.TimestampR\bmergedAt\x120\n" +
	"\tmerged_by\x18& \x01(\v2\x13.maintpb.GithubUserR\bmergedBy\x12*\n" +
	"\x11merge_commit_hash\x18' \x01(\tR\x0fmergeCommitHash\x124\n" +
	"\x04head\x18( \x01(\v2 .maintpb.GithubPullRequestBranchR\x04head\x124\n" +
	"\x04base\x18) \x01(\v2 .maintpb.GithubPullRequestBranchR\x04base\x12H\n" +
	"\x10pr_detail_status\x18* \x01(\v2\x1e.maintpb.GithubIssueSyncStatusR\x0eprDetailStatus\"\x1e\n" +
	"\n" +
	"BoolChange\x12\x10\n" +
	"\x03val\x18\x01 \x01(\bR\x03val\" \n" +
	"\fStringChange\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\"1\n" +
	"\vGithubLabel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"|\n" +
	"\x0fGithubMilestone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x06closed\x18\x03 \x01(\v2\x13.maintpb.BoolChangeR\x06closed\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x03R\x06number\"\x9f\x05\n" +
	"\x10GithubIssueEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12*\n" +
	"\x05label\x18\x05 \x01(\v2\x14.maintpb.GithubLabelR\x05label\x126\n" +
	"\tmilestone\x18\x06 \x01(\v2\x18.maintpb.GithubMilestoneR\tmilestone\x12\x1f\n" +
	"\vassignee_id\x18\a \x01(\x03R\n" +
	"assigneeId\x12\x1f\n" +
	"\vassigner_id\x18\b \x01(\x03R\n" +
	"assignerId\x12-\n" +
	"\x06commit\x18\t \x01(\v2\x15.maintpb.GithubCommitR\x06commit\x12\x1f\n" +
	"\vrename_from\x18\v \x01(\tR\n" +
	"renameFrom\x12\x1b\n" +
	"\trename_to\x18\f \x01(\tR\brenameTo\x12\x1f\n" +
	"\vreviewer_id\x18\r \x01(\x03R\n" +
	"reviewerId\x12.\n" +
	"\x13review_requester_id\x18\x0e \x01(\x03R\x11reviewRequesterId\x128\n" +
	"\rteam_reviewer\x18\x10 \x01(\v2\x13.maintpb.GithubTeamR\fteamReviewer\x12N\n" +
	"\x10dismissed_review\x18\x0f \x01(\v2#.maintpb.GithubDismissedReviewEventR\x0fdismissedReview\x12\x1d\n" +
	"\n" +
	"other_json\x18\n" +
	" \x01(\fR\totherJson\"\x82\x01\n" +
	"\x1aGithubDismissedReviewEvent\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12+\n" +
	"\x11dismissal_message\x18\x03 \x01(\tR\x10dismissalMessage\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05stateJ\x04\b\x02\x10\x03\"U\n" +
	"\fGithubCommit\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1b\n" +
	"\tcommit_id\x18\x03 \x01(\tR\bcommitId\"\x82\x02\n" +
	"\fGithubReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x03R\aactorId\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1b\n" +
	"\tcommit_id\x18\x06 \x01(\tR\bcommitId\x12+\n" +
	"\x11actor_association\x18\a \x01(\tR\x10actorAssociation\x12\x1d\n" +
	"\n" +
	"other_json\x18\b \x01(\fR\totherJson\"T\n" +
	"\x15GithubIssueSyncStatus\x12;\n" +
	"\vserver_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverDate\"\xba\x02\n" +
	"\x1aGithubIssueCommentMutation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x04user\x18\x02 \x01(\v2\x13.maintpb.GithubUserR\x04user\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\aupdated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x123\n" +
	"\breaction\x18\x06 \x03(\v2\x17.maintpb.GithubReactionR\breaction\x12.\n" +
	"\x13removed_reaction_id\x18\a \x03(\x03R\x11removedReactionId\"2\n" +
	"\n" +
	"GithubUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"\x89\x01\n" +
	"\x0eGithubReaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"0\n" +
	"\n" +
	"GithubTeam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"i\n" +
	"\x17GithubPullRequestBranch\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\"\xb2\x01\n" +
	"\vGitMutation\x12$\n" +
	"\x04repo\x18\x01 \x01(\v2\x10.maintpb.GitRepoR\x04repo\x12*\n" +
	"\x06commit\x18\x02 \x01(\v2\x12.maintpb.GitCommitR\x06commit\x12.\n" +
	"\n" +
	"ref_update\x18\x03 \x01(\v2\x0f.maintpb.GitRefR\trefUpdate\x12!\n" +
	"\x03tag\x18\x04 \x01(\v2\x0f.maintpb.GitTagR\x03tag\"6\n" +
	"\aGitRepo\x12\x17\n" +
	"\ago_repo\x18\x01 \x01(\tR\x06goRepo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"d\n" +
	"\tGitCommit\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x121\n" +
	"\tdiff_tree\x18\x03 \x01(\v2\x14.maintpb.GitDiffTreeR\bdiffTree\";\n" +
	"\vGitDiffTree\x12,\n" +
	"\x04file\x18\x01 \x03(\v2\x18.maintpb.GitDiffTreeFileR\x04file\"m\n" +
	"\x0fGitDiffTreeFile\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x14\n" +
	"\x05added\x18\x02 \x01(\x03R\x05added\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\x03R\adeleted\x12\x16\n" +
	"\x06binary\x18\x04 \x01(\bR\x06binary\"O\n" +
	"\x06GitTag\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x1f\n" +
	"\vtarget_hash\x18\x03 \x01(\tR\n" +
	"targetHash\"\xa0\x01\n" +
	"\x0eGerritMutation\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12,\n" +
	"\acommits\x18\x02 \x03(\v2\x12.maintpb.GitCommitR\acommits\x12#\n" +
	"\x04refs\x18\x03 \x03(\v2\x0f.maintpb.GitRefR\x04refs\x12!\n" +
	"\fdeleted_refs\x18\x04 \x03(\tR\vdeletedRefs\".\n" +
	"\x06GitRef\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hashB%Z#golang.org/x/build/maintner/maintpbb\x06proto3"

var (
	file_maintner_proto_rawDescOnce sync.Once
	file_maintner_proto_rawDescData []byte
)

func file_maintner_proto_rawDescGZIP() []byte {
	file_maintner_proto_rawDescOnce.Do(func() {
		file_maintner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maintner_proto_rawDesc), len(file_maintner_proto_rawDesc)))
	})
	return file_maintner_proto_rawDescData
}

var file_maintner_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_maintner_proto_goTypes = []any{
	(*Mutation)(nil),                   // 0: maintpb.Mutation
	(*GithubMutation)(nil),             // 1: maintpb.GithubMutation
	(*GithubIssueMutation)(nil),        // 2: maintpb.GithubIssueMutation
	(*BoolChange)(nil),                 // 3: maintpb.BoolChange
	(*StringChange)(nil),               // 4: maintpb.StringChange
	(*GithubLabel)(nil),                // 5: maintpb.GithubLabel
	(*GithubMilestone)(nil),            // 6: maintpb.GithubMilestone
	(*GithubIssueEvent)(nil),           // 7: maintpb.GithubIssueEvent
	(*GithubDismissedReviewEvent)(nil), // 8: maintpb.GithubDismissedReviewEvent
	(*GithubCommit)(nil),               // 9: maintpb.GithubCommit
	(*GithubReview)(nil),               // 10: maintpb.GithubReview
	(*GithubIssueSyncStatus)(nil),      // 11: maintpb.GithubIssueSyncStatus
	(*GithubIssueCommentMutation)(nil), // 12: maintpb.GithubIssueCommentMutation
	(*GithubUser)(nil),                 // 13: maintpb.GithubUser
	(*GithubReaction)(nil),             // 14: maintpb.GithubReaction
	(*GithubTeam)(nil),                 // 15: maintpb.GithubTeam
	(*GithubPullRequestBranch)(nil),    // 16: maintpb.GithubPullRequestBranch
	(*GitMutation)(nil),                // 17: maintpb.GitMutation
	(*GitRepo)(nil),                    // 18: maintpb.GitRepo
	(*GitCommit)(nil),                  // 19: maintpb.GitCommit
	(*GitDiffTree)(nil),                // 20: maintpb.GitDiffTree
	(*GitDiffTreeFile)(nil),            // 21: maintpb.GitDiffTreeFile
	(*GitTag)(nil),                     // 22: maintpb.GitTag
	(*GerritMutation)(nil),             // 23: maintpb.GerritMutation
	(*GitRef)(nil),                     // 24: maintpb.GitRef
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_maintner_proto_depIdxs = []int32{
	2,  // 0: maintpb.Mutation.github_issue:type_name -> maintpb.GithubIssueMutation
	1,  // 1: maintpb.Mutation.github:type_name -> maintpb.GithubMutation
	17, // 2: maintpb.Mutation.git:type_name -> maintpb.GitMutation
	23, // 3: maintpb.Mutation.gerrit:type_name -> maintpb.GerritMutation
	5,  // 4: maintpb.GithubMutation.labels:type_name -> maintpb.GithubLabel
	6,  // 5: maintpb.GithubMutation.milestones:type_name -> maintpb.GithubMilestone
	13, // 6: maintpb.GithubIssueMutation.user:type_name -> maintpb.GithubUser
	13, // 7: maintpb.GithubIssueMutation.assignees:type_name -> maintpb.GithubUser
	25, // 8: maintpb.GithubIssueMutation.created:type_name -> google.protobuf.Timestamp
	25, // 9: maintpb.GithubIssueMutation.updated:type_name -> google.protobuf.Timestamp
	4,  // 10: maintpb.GithubIssueMutation.body_change:type_name -> maintpb.StringChange
	3,  // 11: maintpb.GithubIssueMutation.closed:type_name -> maintpb.BoolChange
	3,  // 12: maintpb.GithubIssueMutation.locked:type_name -> maintpb.BoolChange
	25, // 13: maintpb.GithubIssueMutation.closed_at:type_name -> google.protobuf.Timestamp
	13, // 14: maintpb.GithubIssueMutation.closed_by:type_name -> maintpb.GithubUser
	5,  // 15: maintpb.GithubIssueMutation.add_label:type_name -> maintpb.GithubLabel
	12, // 16: maintpb.GithubIssueMutation.comment:type_name -> maintpb.GithubIssueCommentMutation
	11, // 17: maintpb.GithubIssueMutation.comment_status:type_name -> maintpb.GithubIssueSyncStatus
	7,  // 18: maintpb.GithubIssueMutation.event:type_name -> maintpb.GithubIssueEvent
	11, // 19: maintpb.GithubIssueMutation.event_status:type_name -> maintpb.GithubIssueSyncStatus
	10, // 20: maintpb.GithubIssueMutation.review:type_name -> maintpb.GithubReview
	11, // 21: maintpb.GithubIssueMutation.review_status:type_name -> maintpb.GithubIssueSyncStatus
	14, // 22: maintpb.GithubIssueMutation.reaction:type_name -> maintpb.GithubReaction
	11, // 23: maintpb.GithubIssueMutation.reaction_status:type_name -> maintpb.GithubIssueSyncStatus
	3,  // 24: maintpb.GithubIssueMutation.draft:type_name -> maintpb.BoolChange
	3,  // 25: maintpb.GithubIssueMutation.merged:type_name -> maintpb.BoolChange
	25, // 26: maintpb.GithubIssueMutation.merged_at:type_name -> google.protobuf.Timestamp
	13, // 27: maintpb.GithubIssueMutation.merged_by:type_name -> maintpb.GithubUser
	16, // 28: maintpb.GithubIssueMutation.head:type_name -> maintpb.GithubPullRequestBranch
	16, // 29: maintpb.GithubIssueMutation.base:type_name -> maintpb.GithubPullRequestBranch
	11, // 30: maintpb.GithubIssueMutation.pr_detail_status:type_name -> maintpb.GithubIssueSyncStatus
	3,  // 31: maintpb.GithubMilestone.closed:type_name -> maintpb.BoolChange
	25, // 32: maintpb.GithubIssueEvent.created:type_name -> google.protobuf.Timestamp
	5,  // 33: maintpb.GithubIssueEvent.label:type_name -> maintpb.GithubLabel
	6,  // 34: maintpb.GithubIssueEvent.milestone:type_name -> maintpb.GithubMilestone
	9,  // 35: maintpb.GithubIssueEvent.commit:type_name -> maintpb.GithubCommit
	15, // 36: maintpb.GithubIssueEvent.team_reviewer:type_name -> maintpb.GithubTeam
	8,  // 37: maintpb.GithubIssueEvent.dismissed_review:type_name -> maintpb.GithubDismissedReviewEvent
	25, // 38: maintpb.GithubReview.created:type_name -> google.protobuf.Timestamp
	25, // 39: maintpb.GithubIssueSyncStatus.server_date:type_name -> google.protobuf.Timestamp
	13, // 40: maintpb.GithubIssueCommentMutation.user:type_name -> maintpb.GithubUser
	25, // 41: maintpb.GithubIssueCommentMutation.created:type_name -> google.protobuf.Timestamp
	25, // 42: maintpb.GithubIssueCommentMutation.updated:type_name -> google.protobuf.Timestamp
	14, // 43: maintpb.GithubIssueCommentMutation.reaction:type_name -> maintpb.GithubReaction
	25, // 44: maintpb.GithubReaction.created:type_name -> google.protobuf.Timestamp
	18, // 45: maintpb.GitMutation.repo:type_name -> maintpb.GitRepo
	19, // 46: maintpb.GitMutation.commit:type_name -> maintpb.GitCommit
	24, // 47: maintpb.GitMutation.ref_update:type_name -> maintpb.GitRef
	22, // 48: maintpb.GitMutation.tag:type_name -> maintpb.GitTag
	20, // 49: maintpb.GitCommit.diff_tree:type_name -> maintpb.GitDiffTree
	21, // 50: maintpb.GitDiffTree.file:type_name -> maintpb.GitDiffTreeFile
	19, // 51: maintpb.GerritMutation.commits:type_name -> maintpb.GitCommit
	24, // 52: maintpb.GerritMutation.refs:type_name -> maintpb.GitRef
	53, // [53:53] is the sub-list for method output_type
	53, // [53:53] is the sub-list for method input_type
	53, // [53:53] is the sub-list for extension type_name
	53, // [53:53] is the sub-list for extension extendee
	0,  // [0:53] is the sub-list for field type_name
}

func init() { file_maintner_proto_init() }
func file_maintner_proto_init() {
	if File_maintner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maintner_proto_rawDesc), len(file_maintner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maintner_proto_goTypes,
		DependencyIndexes: file_maintner_proto_depIdxs,
		MessageInfos:      file_maintner_proto_msgTypes,
	}.Build()
	File_maintner_proto = out.File
	file_maintner_proto_goTypes = nil
	file_maintner_proto_depIdxs = nil
}
